import {ArrowUpRight,Download} from 'lucide-react';
import {Row,fmt} from '@/lib/analysis';

export function LeaguePage({data}:{data:Row}){return <><div className="research-banner">Domestic means the league’s auction category. Player identity, workload and price evidence stay attached to every comparison.</div><div className="league-stats">{[[data.summary.matches,'matches'],[data.summary.players,'source player IDs'],[data.summary.player_seasons,'player-season records'],[8,'franchises']].map(([n,l])=><div key={l}><b>{n}</b><span>{l}</span></div>)}</div><div className="league-seasons">{['2024/25','2025/26'].map(season=>{const teams=data.teams.filter((t:Row)=>t.season===season);return <article key={season}><small>SEASON {season}</small><h2>{teams.find((t:Row)=>t.finish==='Champion')?.team}</h2><p>Champions · 32 matches · 28 league matches and four playoffs.</p><a className="text-cta" href={'/standings?season='+encodeURIComponent(season)}>Explore the season <ArrowUpRight/></a></article>})}</div><div className="research-links"><a className="hero-cta" href="/players">Explore domestic players <ArrowUpRight/></a><a className="text-cta" href="/matches">Explore match results <ArrowUpRight/></a></div></>}
export function ResearchPage({data}:{data:Row}){
 const roles=data.players.filter((p:Row)=>p.domestic_status==='Domestic'&&p.role!=='Unknown').length;
 return <section className="panel prose"><small>RESEARCH RECORD</small><h2>The data, and what remains unresolved.</h2><p>The original ball-by-ball-derived performance file is preserved. The analysis joins identity and acquisition evidence without silently turning missing information into zero.</p><div className="league-stats">{[[data.summary.domestic_rows,'documented domestic rows'],[roles,'domestic rows with a recorded role'],[data.summary.exact_price_rows,'eligible exact-price rows'],[data.players.filter((p:Row)=>p.assumed_retained_price_npr!=null).length,'retained-price scenario rows']].map(([n,l])=><div key={l}><b>{n}</b><span>{l}</span></div>)}</div><div className="research-links"><a className="hero-cta" href="/npl_analysis_master.csv" download>Analysis CSV <Download size={17}/></a><a className="text-cta" href="/data/dictionary.json" download>Data dictionary <ArrowUpRight size={17}/></a><a className="text-cta" href="/data/qa-report.json" download>QA report <ArrowUpRight size={17}/></a></div><h3>Coverage before conclusions</h3><p>{data.summary.unknown_rows} player-season records have unverified domestic classification. Unknown does not mean foreign. Recorded roles come from the 2025 auction pool; a missing role limits role-specific comparison.</p><p>Unsold auction outcomes are separate evidence. The {data.unsold?.length||0} unique names do not become zero-price contracts or fabricated performance rows. A later replacement signing can follow an unsold auction outcome.</p><h3>Questions this dataset can address</h3><ul><li>How do scoring rates and wicket-taking change across phases?</li><li>Which players combine production with consistent innings-level performance?</li><li>How do observed prices compare with performance within a qualified role-season cohort?</li></ul><p>These comparisons are descriptive. Injury, availability, scouting assessments and contract incentives are not fully observed.</p><h3>Review log</h3><div className="research-issues">{data.issues.map((x:Row,i:number)=><article key={i}><h3>{x.kind}</h3><p>{x.detail}</p></article>)}</div></section>
}
export function SourcesPage({data}:{data:Row}){return <section className="panel prose"><small>SOURCE REGISTRY</small><h2>Evidence you can follow.</h2><p>Prefer CAN and official league announcements when available, then documented reporting for cross-checks. A listed source is not automatically official; supplementary sources do not overwrite the performance master.</p><div className="source-list">{data.sources.map((s:Row)=><article className="source-card" key={s.source_id}><small>{s.source_id}</small><h3>{s.publication}</h3><p>Published: {s.published_date||'Not recorded'} · Accessed: {s.accessed_date}</p><a className="source" href={s.url} target="_blank" rel="noreferrer">Open original source <ArrowUpRight size={16}/></a></article>)}</div><h3>User-supplied evidence</h3><p>The 2024 auction list, 2025 auction and unsold lists, retained-price rule and separate-player identity clarification were supplied in this project. They remain distinguished from independently reported facts.</p><h3 id="visual-credits">Visual credits</h3><p>The homepage uses the <a href="https://npl-t20.com/" target="_blank" rel="noreferrer">Nepal Premier League logo</a> to identify the league. Rights belong to its owner. This is an independent analysis website.</p></section>}
