"use client";
import {useState} from 'react';
import {ArrowUpRight,Menu} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import GlobalSearch from './global-search';
import {destinations} from '@/lib/navigation';
const groups=[{name:'Explore cricket',paths:['league','players','teams','matches','standings']},{name:'Analyse performance & cost',paths:['cost-analysis','value-lab','compare','trust-index','auction']},{name:'Check the evidence',paths:['research','methodology','sources','data','qa']}];
export default function SiteHeader({current='Home',onNavigate}:{current?:string,onNavigate?:(view:string)=>void}){
 const[open,setOpen]=useState(false);
 const primary=['players','teams','cost-analysis','trust-index'];
 return <><a className="skiplink" href="#main-content">Skip to content</a><header className="site-header"><a className="brand" href="/" aria-label="Nepal Premier League Analysis home"><span>NPL</span><b className="brand-label">Nepal Premier League<small>Analysis</small></b></a><nav aria-label="Primary" className="quicknav"><a href="/" aria-current={current==='Home'?'page':undefined}>Home</a>{destinations.filter(d=>primary.includes(d.path)).map(d=><a key={d.path} href={'/'+d.path} aria-current={current===d.view?'page':undefined}>{d.name}</a>)}</nav><GlobalSearch/><button className="menu-trigger" onClick={()=>setOpen(true)} aria-label="Open navigation menu">All sections <Menu size={21}/></button></header>{current!=='Home'&&<nav className="section-strip" aria-label="Analysis sections">{destinations.filter(d=>['players','teams','matches','standings','cost-analysis','value-lab','compare','trust-index'].includes(d.path)).map(d=><a key={d.path} href={'/'+d.path} aria-current={current===d.view?'page':undefined}>{d.name}</a>)}</nav>}<Dialog open={open} onOpenChange={setOpen}><DialogContent className="mega-menu"><div className="menu-heading"><DialogTitle>Where would you like to go?</DialogTitle><DialogDescription>Players, results, spending and the evidence behind the numbers.</DialogDescription></div><div className="nav-groups">{groups.map(g=><section key={g.name}><h3>{g.name}</h3><nav aria-label={g.name}>{g.paths.map(path=>{const d=destinations.find(d=>d.path===path);return d&&<a href={'/'+d.path} key={path} onClick={()=>setOpen(false)} aria-current={current===d.view?'page':undefined}><div>{d.name}<small>{d.description}</small></div><ArrowUpRight size={18}/></a>})}</nav></section>)}</div><div className="menu-bottom"><a href="/">Back to home</a><a href="/data">Download data & check coverage</a></div></DialogContent></Dialog></>;
}
